# Generated by Django 3.1.3 on 2020-12-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='name',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='urls',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
