# Generated by Django 3.0.8 on 2020-07-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='user_id',
            new_name='user',
        ),
    ]
