# Generated by Django 3.0.6 on 2020-06-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='urls',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
