# Generated by Django 3.0.6 on 2020-06-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='urls',
        ),
    ]
