# Generated by Django 3.0.7 on 2020-06-18 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_url_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='user',
        ),
        migrations.AddField(
            model_name='url',
            name='user',
            field=models.ManyToManyField(related_name='user_url', to=settings.AUTH_USER_MODEL),
        ),
    ]
