# Generated by Django 3.0.7 on 2020-06-18 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200618_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='owner',
        ),
        migrations.AddField(
            model_name='url',
            name='user_url',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
