# Generated by Django 3.0.7 on 2020-06-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='created_by',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
