# Generated by Django 3.0.7 on 2020-06-14 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_url_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='created_by',
        ),
        migrations.AddField(
            model_name='url',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
