# Generated by Django 3.0.7 on 2020-06-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20200614_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='user',
        ),
    ]
